{
 "title": "eRT3_Sushi_Dashboard",
 "time": { "from": "now-6h", "to": "now-4h" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "eui",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"sushiSensor\", tag: \"eui\")"
   }
  ]
 },
 "panels": [
  { "title": "Meta Data: ${eui}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "eui" },
  {
   "title": "Sushi Sensor Table Display",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r[\"data_type\"] == \"meta_data\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"meta_data\")"
    }
   ]
  },
  { "title": "Pressure Sensor: ${eui}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "eui" },
  {
   "title": "Sushi Sensor Digital Display",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "// Pressure, to change the display names to something more visable, do the following\r\n// On the right-hand panel: Add \"field override\" > \"Fields with name\" (select the parameter- choose the names seen on the display currently) > \"Add override property\" > \"Standard options > Display name\" (enter the name you wish to display)\r\n\r\n// Simply copy and paste the following block of code to add more parameters. Change \"r._field\" value to the name of the parameter in the database.\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press\")\r\n\r\n"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press_stat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press_stat\")\r\n\r\n"
    },
    {
     "query": "// Temp\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n  \r\n  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press_temp\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press_temp\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press_temp_stat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press_temp_stat\")"
    }
   ]
  },
  {
   "title": "Sushi Sensor Trend Display",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "// Pressure, to change the display names to something more visable, do the following\r\n// On the right-hand panel: Add \"field override\" > \"Fields with name\" (select the parameter- choose the names seen on the display currently) > \"Add override property\" > \"Standard options > Display name\" (enter the name you wish to display)\r\n\r\n// Simply copy and paste the following block of code to add more parameters. Change \"r._field\" value to the name of the parameter in the database.\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press\")\r\n\r\n"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press_stat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press_stat\")\r\n\r\n"
    },
    {
     "query": "// Temp\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n  \r\n  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press_temp\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press_temp\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press_temp_stat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press_temp_stat\")"
    }
   ]
  },
  { "title": "Temperature Sensor: ${eui}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "eui" },
  {
   "title": "Sushi Sensor Digital Display",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "// Temp1, to change the display names to something more visable, do the following\r\n// On the right-hand panel: Add \"field override\" > \"Fields with name\" (select the parameter- choose the names seen on the display currently) > \"Add override property\" > \"Standard options > Display name\" (enter the name you wish to display)\r\n\r\n// Simply copy and paste the following block of code to add more parameters. Change \"r._field\" value to the name of the parameter in the database.\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"temp1\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"temp1\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"temp1stat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"temp1stat\")\r\n\r\n"
    },
    {
     "query": "// Temp2\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n  \r\n  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"temp2\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"temp2\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"temp2stat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"temp2stat\")"
    }
   ]
  },
  {
   "title": "Sushi Sensor Trend Display",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "// Pressure, to change the display names to something more visable, do the following\r\n// On the right-hand panel: Add \"field override\" > \"Fields with name\" (select the parameter- choose the names seen on the display currently) > \"Add override property\" > \"Standard options > Display name\" (enter the name you wish to display)\r\n\r\n// Simply copy and paste the following block of code to add more parameters. Change \"r._field\" value to the name of the parameter in the database.\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press\")\r\n\r\n"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press_stat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press_stat\")\r\n\r\n"
    },
    {
     "query": "// Temp\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n  \r\n  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press_temp\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press_temp\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"press_temp_stat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"press_temp_stat\")"
    }
   ]
  },
  { "title": "Vibration Sensor: ${eui}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "repeat": "eui" },
  {
   "title": "Sushi Sensor Digital Display",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "// Z-axis parameters, to change the display names to something more visable, do the following\r\n// On the right-hand panel: Add \"field override\" > \"Fields with name\" (select the parameter- choose the names seen on the display currently) > \"Add override property\" > \"Standard options > Display name\" (enter the name you wish to display)\r\n\r\n// Simply copy and paste the following block of code to add more parameters. Change \"r._field\" value to the name of the parameter in the database.\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"temp\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"temp\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"zacc\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"zacc\")"
    },
    {
     "query": "from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"zvel\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"zvel\")\r\n"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"zstat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"zstat\")"
    },
    {
     "query": "// X-axis parameters\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xacc\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xacc\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xvel\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xvel\")"
    },
    {
     "query": "from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xstat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xstat\")"
    },
    {
     "query": "// Y-axis paramters\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"yacc\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"yacc\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"yvel\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"yvel\")"
    },
    {
     "query": "from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"ystat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"ystat\")"
    },
    {
     "query": "// XYZ-axis parameters\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xyzacc\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xyzacc\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xyzvel\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xyzvel\")"
    },
    {
     "query": "from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xyzstat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xyzstat\")"
    }
   ]
  },
  {
   "title": "Sushi Sensor Trend Display",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "// Z-axis parameters, to change the display names to something more visable, do the following\r\n// On the right-hand panel: Add \"field override\" > \"Fields with name\" (select the parameter- choose the names seen on the display currently) > \"Add override property\" > \"Standard options > Display name\" (enter the name you wish to display)\r\n\r\n// Simply copy and paste the following block of code to add more parameters. Change \"r._field\" value to the name of the parameter in the database.\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"temp\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"temp\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"zacc\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"zacc\")"
    },
    {
     "query": "from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"zvel\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"zvel\")\r\n"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"zstat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"zstat\")"
    },
    {
     "query": "// X-axis parameters\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xacc\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xacc\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xvel\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xvel\")"
    },
    {
     "query": "from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xstat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xstat\")"
    },
    {
     "query": "// Y-axis paramters\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"yacc\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"yacc\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"yvel\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"yvel\")"
    },
    {
     "query": "from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"ystat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"ystat\")"
    },
    {
     "query": "// XYZ-axis parameters\r\n// Enable the query if you wish to use by clicking the \"eye\" icon\r\n\r\nfrom(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xyzacc\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xyzacc\")"
    },
    {
     "query": "  from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xyzvel\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xyzvel\")"
    },
    {
     "query": "from(bucket: \"sushiSensor\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"sushi\" and r._field == \"xyzstat\" and r[\"eui\"] == \"${eui}\")\r\n  |> yield(name: \"xyzstat\")"
    }
   ]
  }
 ]
}